import Head from "next/head";
import {Card, CardContent, CardHeader} from "~/components/ui/card";
import {Button} from "~/components/ui/button";
import React from "react";
import {Input} from "~/components/ui/input";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center justify-center p-24 w-full bg-background">
        <Card>
          <CardHeader>
            <Input
                type="password"
                placeholder="PASSWORD"
                onChange={(e) => (e.target.value)}
            />
          </CardHeader>
          <CardContent className="flex justify-center">
            <Button className="w-full" onClick={()=> null}>
              Submit
            </Button>
          </CardContent>
        </Card>
      </main>
    </>
  );
}
