import Head from "next/head";
import {Button} from "~/components/ui/button";
import React, { useState} from "react";
import {Input} from "~/components/ui/input";
import {Background} from "~/components/ui/background";
import {env} from "~/env";
//import {Rock, RockProps} from "~/components/ui/rock";

export default function Home() {
    const [value, setValue] = useState("");

    //const rockRef = useRef<RockProps>(null);

    const onSubmit = () => {
        if (value !== env.NEXT_PUBLIC_PASSCODE) {
            setValue("")
            /*if (!rockRef.current) return
             rockRef.current.handleRock()*/
            return
        }
    }

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className="flex items-center justify-center p-24 w-full min-h-screen ">
                <Background/>
                <div className='flex gap-4'>
                    <Input
                        type="password"
                        placeholder="PASSWORD"
                        value={value}
                        onChange={(v) => setValue(v.target.value)}
                    />
                    <Button onClick={onSubmit}>{"->"}</Button>
                </div>
            </main>
        </>
    );
}
