name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.18.0]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Create env file
      run: |
          touch .env
          echo NEXT_PUBLIC_PASSCODE=${{ secrets.NEXT_PUBLIC_PASSCODE }} >> .env
          cat .env
    - run: npm ci
    - run: npm run build --if-present
    - name: Change Directory
      run: cd /home/pi/actions-runner/_work/lab/lab
    - run: pm2 restart 0
